Wine.create(name: 'Fantastic Cabernet Sauvignon', image_url: 'wine1.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '15.00')

Wine.create(name: 'Joyful Merlot', image_url: 'wine5.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '20.75')

Wine.create(name: 'Joyful Freedom', image_url: 'wine5.jpg', description: 'Overwhelming sensations. Never will you want for any other beverage every again. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '1.99')

Wine.create(name: 'Delicious Formula', image_url: 'wine3.jpg', description: 'Taste like a whole lot of fancy fresh. Free monocle with every purchase! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '18.75')

Wine.create(name: 'Unescapable Cheer', image_url: 'wine3.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '25.00')

Wine.create(name: 'Arousing Again', image_url: 'wine2.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '7.49')

Wine.create(name: 'Delicious Classic', image_url: 'wine2.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '26.29')

Wine.create(name: 'Forever Result', image_url: 'wine2.jpg', description: 'Taste like a whole lot of fancy fresh. Free monocle with every purchase! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '4.29')

Wine.create(name: 'Pretentious Cheer', image_url: 'wine6.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '9.49')

Wine.create(name: 'Pretentious Experience', image_url: 'wine1.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '13.50')

Wine.create(name: 'Delicious Carmenere', image_url: 'wine3.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '8.00')

Wine.create(name: 'Rolling Experience', image_url: 'wine4.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '27.97')

Wine.create(name: 'Joyful Cabernet Sauvignon', image_url: 'wine6.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '4.75')

Wine.create(name: 'New Cheer', image_url: 'wine1.jpg', description: 'Could taste like you went to heaven and died, but nobody here knows what that is really like so we are just guessing. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '16.95')

Wine.create(name: 'New Partner', image_url: 'wine6.jpg', description: 'Taste like a whole lot of fancy fresh. Free monocle with every purchase! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '23.97')

Wine.create(name: 'The Partner', image_url: 'wine2.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '13.29')

Wine.create(name: 'Maybe Wine', image_url: 'wine4.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '13.49')

Wine.create(name: 'The Sangiovese', image_url: 'wine6.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '24.29')

Wine.create(name: 'Tasty Liquid', image_url: 'wine6.jpg', description: 'Overwhelming sensations. Never will you want for any other beverage every again. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '3.29')

Wine.create(name: 'All Meadows', image_url: 'wine2.jpg', description: 'Supurbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '25.95')

Wine.create(name: 'Spicy Formula', image_url: 'wine4.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '21.29')

Wine.create(name: 'Maybe Meadows', image_url: 'wine6.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '15.99')

Wine.create(name: 'The Taste', image_url: 'wine3.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '21.75')

Wine.create(name: 'Rose Champagne', image_url: 'wine1.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '24.50')

Wine.create(name: 'Delicious Formula', image_url: 'wine1.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '18.50')

Wine.create(name: 'Complete Formula', image_url: 'wine4.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '18.50')

Wine.create(name: 'Tasty Vineyard', image_url: 'wine5.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '10.95')

Wine.create(name: 'Maybe Merlot', image_url: 'wine4.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '28.97')

Wine.create(name: 'The Sangiovese', image_url: 'wine5.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '7.49')

Wine.create(name: 'Forever Creek', image_url: 'wine3.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '23.97')

Wine.create(name: 'Tasty Freedom', image_url: 'wine3.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '22.00')

Wine.create(name: 'Pretentious Sangiovese', image_url: 'wine5.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '12.50')

Wine.create(name: 'Rolling Sangiovese', image_url: 'wine5.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '13.49')

Wine.create(name: 'Little Wine', image_url: 'wine3.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '18.49')

Wine.create(name: 'Rolling Champagne', image_url: 'wine5.jpg', description: 'Taste like a whole lot of fancy fresh. Free monocle with every purchase! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '17.99')

Wine.create(name: 'Rolling Wine', image_url: 'wine5.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '15.95')

Wine.create(name: 'Fancy Again', image_url: 'wine3.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '5.97')

Wine.create(name: 'Tasty Creek', image_url: 'wine5.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '25.00')

Wine.create(name: 'Fantastic Brew', image_url: 'wine3.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '3.99')

Wine.create(name: 'All Partner', image_url: 'wine5.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '11.99')

Wine.create(name: 'Tasty Merlot', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '21.95')

Wine.create(name: 'Unescapable Partner', image_url: 'wine1.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '11.00')

Wine.create(name: 'The Experience', image_url: 'wine5.jpg', description: 'Supurbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '10.29')

Wine.create(name: 'All Classic', image_url: 'wine1.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '21.75')

Wine.create(name: 'Pretentious Hills', image_url: 'wine3.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '5.29')

Wine.create(name: 'Unescapable Champagne', image_url: 'wine4.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '28.29')

Wine.create(name: 'New Cheer', image_url: 'wine1.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '7.50')

Wine.create(name: 'Tasty Hills', image_url: 'wine5.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '28.97')

Wine.create(name: 'Arousing Again', image_url: 'wine2.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '22.49')

Wine.create(name: 'Rose Creek', image_url: 'wine1.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '4.99')

Wine.create(name: 'Maybe Cabernet Sauvignon', image_url: 'wine6.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '28.99')

Wine.create(name: 'Arousing Again', image_url: 'wine1.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '8.75')

Wine.create(name: 'Joyful Merlot', image_url: 'wine6.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '23.95')

Wine.create(name: 'Rose Experience', image_url: 'wine3.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '2.29')

Wine.create(name: 'Tasty Friend', image_url: 'wine4.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '25.49')

Wine.create(name: 'Complete Brew', image_url: 'wine6.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '29.75')

Wine.create(name: 'Joyful Merlot', image_url: 'wine2.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '6.49')

Wine.create(name: 'Delicious Carmenere', image_url: 'wine2.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '12.00')

Wine.create(name: 'Delicious Experience', image_url: 'wine1.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '2.00')

Wine.create(name: 'Delicious Constable\'s', image_url: 'wine5.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '2.97')

Wine.create(name: 'Complete Champagne', image_url: 'wine6.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '6.29')

Wine.create(name: 'Rolling Wine', image_url: 'wine2.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '27.75')

Wine.create(name: 'New Brew', image_url: 'wine3.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '23.99')

Wine.create(name: 'Little Carmenere', image_url: 'wine4.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '4.75')

Wine.create(name: 'Delicious Again', image_url: 'wine6.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '29.75')

Wine.create(name: 'Unescapable Wine', image_url: 'wine3.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '13.75')

Wine.create(name: 'Pretentious Meadows', image_url: 'wine1.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '6.50')

Wine.create(name: 'Unescapable Cheer', image_url: 'wine2.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '26.95')

Wine.create(name: 'Rolling Liquid', image_url: 'wine4.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '1.95')

Wine.create(name: 'Little Cabernet Sauvignon', image_url: 'wine2.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '29.75')

Wine.create(name: 'Maybe Vineyard', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '22.99')

Wine.create(name: 'Complete Carmenere', image_url: 'wine6.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '3.95')

Wine.create(name: 'White Cheer', image_url: 'wine4.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '8.50')

Wine.create(name: 'Unescapable Again', image_url: 'wine6.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '8.99')

Wine.create(name: 'Tasty Result', image_url: 'wine6.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '26.49')

Wine.create(name: 'Maybe Sangiovese', image_url: 'wine6.jpg', description: 'Overwhelming sensations. Never will you want for any other beverage every again. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '17.49')

Wine.create(name: 'White Sangiovese', image_url: 'wine5.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '24.75')

Wine.create(name: 'Complete Cheer', image_url: 'wine5.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '29.00')

Wine.create(name: 'Fantastic Result', image_url: 'wine1.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '7.50')

Wine.create(name: 'Unescapable Cheer', image_url: 'wine4.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '23.75')

Wine.create(name: 'Complete Experience', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '19.95')

Wine.create(name: 'Arousing Merlot', image_url: 'wine5.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '9.00')

Wine.create(name: 'Rolling Champagne', image_url: 'wine4.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '6.97')

Wine.create(name: 'Complete Liquid', image_url: 'wine6.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '27.97')

Wine.create(name: 'Joyful Wine', image_url: 'wine5.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '3.97')

Wine.create(name: 'White Again', image_url: 'wine6.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '5.99')

Wine.create(name: 'Arousing Partner', image_url: 'wine1.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '18.75')

Wine.create(name: 'Rose Classic', image_url: 'wine1.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '6.50')

Wine.create(name: 'Maybe Champagne', image_url: 'wine1.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '20.29')

Wine.create(name: 'Delicious Carmenere', image_url: 'wine1.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '7.49')

Wine.create(name: 'Fantastic Abracadabra', image_url: 'wine5.jpg', description: 'Could taste like you went to heaven and died, but nobody here knows what that is really like so we are just guessing. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '7.49')

Wine.create(name: 'Rolling Partner', image_url: 'wine4.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '28.00')

Wine.create(name: 'Rose Result', image_url: 'wine1.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '8.00')

Wine.create(name: 'Rolling Creek', image_url: 'wine2.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '11.49')

Wine.create(name: 'The Partner', image_url: 'wine2.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '8.95')

Wine.create(name: 'Fantastic Merlot', image_url: 'wine3.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '27.75')

Wine.create(name: 'Fancy Abracadabra', image_url: 'wine1.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '5.49')

Wine.create(name: 'Delicious Liquid', image_url: 'wine3.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '8.75')

Wine.create(name: 'Forever Wine', image_url: 'wine4.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '26.00')

Wine.create(name: 'Arousing Merlot', image_url: 'wine1.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '17.97')
