Wine.delete_all
Order.delete_all
# -----
Wine.create(name: 'Complete Merlot', image_url: 'wine4.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '17.75')

Wine.create(name: 'Forever Sangiovese', image_url: 'wine5.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '10.95')

Wine.create(name: 'Arousing Again', image_url: 'wine4.jpg', description: 'Overwhelming sensations. Never will you want for any other beverage every again. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '28.00')

Wine.create(name: 'Little Formula', image_url: 'wine5.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '20.29')

Wine.create(name: 'Rose Freedom', image_url: 'wine3.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '9.75')

Wine.create(name: 'Forever Meadows', image_url: 'wine4.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '26.00')

Wine.create(name: 'Delicious Wine', image_url: 'wine3.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '27.75')

Wine.create(name: 'The Friend', image_url: 'wine4.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '23.00')

Wine.create(name: 'White Hills', image_url: 'wine3.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '28.95')

Wine.create(name: 'Tasty Again', image_url: 'wine4.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '16.95')

Wine.create(name: 'Fancy Cabernet Sauvignon', image_url: 'wine6.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '29.95')

Wine.create(name: 'Rose Again', image_url: 'wine4.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '23.00')

Wine.create(name: 'Spicy Partner', image_url: 'wine4.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '7.97')

Wine.create(name: 'New Hills', image_url: 'wine1.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '4.50')

Wine.create(name: 'Tasty Constable\'s', image_url: 'wine3.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '25.95')

Wine.create(name: 'White Friend', image_url: 'wine3.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '20.75')

Wine.create(name: 'Complete Luck', image_url: 'wine3.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '29.75')

Wine.create(name: 'All Formula', image_url: 'wine2.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '7.49')

Wine.create(name: 'The Brew', image_url: 'wine4.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '13.49')

Wine.create(name: 'Unescapable Taste', image_url: 'wine4.jpg', description: 'You will come to find yourself a week after drinking this wine wondering if it was truly non-alcoholic after you. Your new frineds think you are great, though. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '12.95')

Wine.create(name: 'Fantastic Constable\'s', image_url: 'wine5.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '9.99')

Wine.create(name: 'Unescapable Result', image_url: 'wine2.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '9.50')

Wine.create(name: 'All Partner', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '8.50')

Wine.create(name: 'Tasty Carmenere', image_url: 'wine1.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '16.99')

Wine.create(name: 'New Carmenere', image_url: 'wine2.jpg', description: 'Spiced and warmed, this drink will keep you warm through any season. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '10.50')

Wine.create(name: 'Rose Friend', image_url: 'wine3.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '9.50')

Wine.create(name: 'Fancy Formula', image_url: 'wine5.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '22.95')

Wine.create(name: 'Rolling Again', image_url: 'wine5.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '16.49')

Wine.create(name: 'Rose Luck', image_url: 'wine1.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '20.99')

Wine.create(name: 'Pretentious Cheer', image_url: 'wine5.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '29.50')

Wine.create(name: 'Joyful Cheer', image_url: 'wine5.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '11.29')

Wine.create(name: 'Joyful Freedom', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '9.75')

Wine.create(name: 'Fantastic Luck', image_url: 'wine5.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '8.75')

Wine.create(name: 'Fancy Formula', image_url: 'wine2.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '29.29')

Wine.create(name: 'Unescapable Cheer', image_url: 'wine5.jpg', description: 'Overwhelming sensations. Never will you want for any other beverage every again. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '18.29')

Wine.create(name: 'All Classic', image_url: 'wine3.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '10.50')

Wine.create(name: 'Complete Classic', image_url: 'wine3.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '25.99')

Wine.create(name: 'Little Abracadabra', image_url: 'wine6.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '14.49')

Wine.create(name: 'Rose Abracadabra', image_url: 'wine6.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '24.95')

Wine.create(name: 'Arousing Abracadabra', image_url: 'wine6.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '18.99')

Wine.create(name: 'Complete Wine', image_url: 'wine2.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '16.29')

Wine.create(name: 'Forever Hills', image_url: 'wine6.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '10.50')

Wine.create(name: 'Arousing Friend', image_url: 'wine3.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '19.29')

Wine.create(name: 'All Freedom', image_url: 'wine4.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '15.50')

Wine.create(name: 'Fantastic Meadows', image_url: 'wine3.jpg', description: 'Uncondescending wine made for those with a bit of pazazz in their life, who just can not get enough excitment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '14.97')

Wine.create(name: 'Complete Taste', image_url: 'wine3.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '19.29')

Wine.create(name: 'Little Cabernet Sauvignon', image_url: 'wine1.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '20.99')

Wine.create(name: 'Rolling Hills', image_url: 'wine6.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '8.75')

Wine.create(name: 'Delicious Again', image_url: 'wine3.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '25.29')

Wine.create(name: 'Joyful Brew', image_url: 'wine6.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '4.97')

Wine.create(name: 'White Cabernet Sauvignon', image_url: 'wine2.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '8.29')

Wine.create(name: 'Rose Freedom', image_url: 'wine4.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '3.50')

Wine.create(name: 'Maybe Cabernet Sauvignon', image_url: 'wine2.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '1.75')

Wine.create(name: 'Complete Champagne', image_url: 'wine3.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '11.99')

Wine.create(name: 'The Merlot', image_url: 'wine4.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '16.50')

Wine.create(name: 'Forever Partner', image_url: 'wine5.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '20.49')

Wine.create(name: 'Joyful Taste', image_url: 'wine5.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '24.00')

Wine.create(name: 'Delicious Constable\'s', image_url: 'wine1.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '16.99')

Wine.create(name: 'Complete Vineyard', image_url: 'wine4.jpg', description: 'Contain your joy as you indulge in this overbearing apple filled drink that will take you to another world. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '29.75')

Wine.create(name: 'Pretentious Experience', image_url: 'wine6.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '4.75')

Wine.create(name: 'Fantastic Formula', image_url: 'wine4.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '3.95')

Wine.create(name: 'Tasty Sangiovese', image_url: 'wine5.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '24.75')

Wine.create(name: 'Complete Partner', image_url: 'wine2.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '19.97')

Wine.create(name: 'The Result', image_url: 'wine3.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '9.99')

Wine.create(name: 'The Hills', image_url: 'wine5.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '4.49')

Wine.create(name: 'All Experience', image_url: 'wine6.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '14.49')

Wine.create(name: 'Spicy Partner', image_url: 'wine5.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '21.50')

Wine.create(name: 'Rose Merlot', image_url: 'wine1.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '10.29')

Wine.create(name: 'All Carmenere', image_url: 'wine6.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '9.75')

Wine.create(name: 'Maybe Cabernet Sauvignon', image_url: 'wine1.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Bulgaria', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '18.97')

Wine.create(name: 'Fancy Luck', image_url: 'wine2.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'England', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '7.49')

Wine.create(name: 'All Liquid', image_url: 'wine1.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '8.95')

Wine.create(name: 'Spicy Creek', image_url: 'wine5.jpg', description: 'Makes sense when drunk with an actual alcoholic wine, by itself just tastes like water. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '25.00')

Wine.create(name: 'Fancy Partner', image_url: 'wine1.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '14.75')

Wine.create(name: 'Rolling Friend', image_url: 'wine1.jpg', description: 'Have you ever tasted a wine so brilliant? No, I thought not. Try this delicious drink, now. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '10.49')

Wine.create(name: 'Tasty Merlot', image_url: 'wine1.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '11.99')

Wine.create(name: 'Complete Wine', image_url: 'wine4.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Red', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '14.97')

Wine.create(name: 'Rose Liquid', image_url: 'wine6.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '350ml', price: '6.00')

Wine.create(name: 'Spicy Friend', image_url: 'wine3.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '20ml', price: '29.00')

Wine.create(name: 'Arousing Taste', image_url: 'wine1.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '4.95')

Wine.create(name: 'Tasty Champagne', image_url: 'wine6.jpg', description: 'Blended in the fires out Mt Doom, this drink will leave you yelling GOLLUM repeatedly until you can not remember your name. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '28.49')

Wine.create(name: 'Maybe Partner', image_url: 'wine2.jpg', description: 'Made from the ravings of a very drunk book store owner and their troll-like friend, using a cheaper wine and a bit of a branch. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '20.49')

Wine.create(name: 'Maybe Meadows', image_url: 'wine4.jpg', description: 'Superbly made by wolves, although we do not know how. They work tirelessly to bring you this joy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '1.00')

Wine.create(name: 'The Classic', image_url: 'wine4.jpg', description: 'A friendly beginning for your days end. Maybe the end of time, even. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'China', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '500ml', price: '28.75')

Wine.create(name: 'All Partner', image_url: 'wine4.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Ireland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '28.97')

Wine.create(name: 'New Champagne', image_url: 'wine4.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '20.29')

Wine.create(name: 'Pretentious Luck', image_url: 'wine6.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '27.29')

Wine.create(name: 'Forever Again', image_url: 'wine2.jpg', description: 'A bit soft around the edges but otherwise an amazing wine, made with only the purest of tears. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Scotland', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '2.50')

Wine.create(name: 'Maybe Cabernet Sauvignon', image_url: 'wine6.jpg', description: 'You will come to find yourself a week after drinking this wine wondering if it was truly non-alcoholic after you. Your new frineds think you are great, though. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Siberia', grape_type: 'White', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '11.95')

Wine.create(name: 'New Merlot', image_url: 'wine2.jpg', description: 'Oranges, apples, strawberries and a hint of mango. You will find non of those in this drink. Only tar. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '15.49')

Wine.create(name: 'Maybe Brew', image_url: 'wine5.jpg', description: 'Aggressively powerful taste of lemon that you just can not place. The scents of spices will leave you nostalgic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Australia', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '175ml', price: '10.29')

Wine.create(name: 'Maybe Partner', image_url: 'wine1.jpg', description: 'Delicious cherries and berries mixed well with a bull hair mixer over yonder. Dreams of becoming a cowboy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '500ml', price: '1.97')

Wine.create(name: 'Fantastic Carmenere', image_url: 'wine3.jpg', description: 'Matured to perfection and then left a little too long, this wine is still good and full of juicy flavour. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'Red', suitable_for_vegetarians: 'false', bottle_size: '350ml', price: '26.97')

Wine.create(name: 'Delicious Abracadabra', image_url: 'wine6.jpg', description: 'Splendid mix of little grapey bits and some other spices and made in some vineyard you have never heard of. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Russia', grape_type: 'Black', suitable_for_vegetarians: 'false', bottle_size: '250ml', price: '19.75')

Wine.create(name: 'Fantastic Wine', image_url: 'wine5.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '1 litre', price: '3.00')

Wine.create(name: 'White Luck', image_url: 'wine2.jpg', description: '1997 blend, saved for somebody else but now sold here because they decided they no longer liked us. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '15.50')

Wine.create(name: 'White Cabernet Sauvignon', image_url: 'wine1.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Someplace Nice', grape_type: 'White', suitable_for_vegetarians: 'true', bottle_size: '250ml', price: '17.99')

Wine.create(name: 'Joyful Friend', image_url: 'wine1.jpg', description: 'Juicy and robust, this wine will have you screaming for more. Loudly. Much fruit in it! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'USA', grape_type: 'Green', suitable_for_vegetarians: 'false', bottle_size: '1 litre', price: '9.50')

Wine.create(name: 'Rose Partner', image_url: 'wine5.jpg', description: 'A dash of red, a dash of blue, and this wine will not ever make fun of you. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Wales', grape_type: 'Green', suitable_for_vegetarians: 'true', bottle_size: '20ml', price: '4.00')

Wine.create(name: 'Tasty Brew', image_url: 'wine6.jpg', description: 'If you could shove a whole turkey into your mouth and then dissolved it with cherry cola, you would feel like you were drinking this wine. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', country_of_origin: 'Eorzea', grape_type: 'Black', suitable_for_vegetarians: 'true', bottle_size: '175ml', price: '10.97')
